
import { InventoryItem } from '@/types';

export const mockInventoryItems: InventoryItem[] = [
  {
    id: '1',
    name: 'Parmigiano Reggiano',
    description: 'Aged 24 months, imported from Italy',
    sku: 'PR-24-001',
    category: 'Cheese',
    subcategory: 'Hard Cheese',
    unit: 'kg',
    unitCost: 28.5,
    quantityOnHand: 12,
    reorderPoint: 5,
    reorderQuantity: 10,
    supplierId: 'supplier-1',
    notes: 'Premium quality',
    defaultSupplierId: 'supplier-1',
    defaultSupplierName: 'Italian Imports Co.',
    cost: 28.5,
    currentStock: 12,
    lowStockThreshold: 5,
    storageLocation: 'Walk-in Cooler',
    expirationDate: '2025-08-15',
    lotNumber: 'IT2024-05',
    imageUrl: '/placeholder.svg',
    markupPercentage: 40,
    lastCountDate: '2025-05-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '2',
    name: 'Cabernet Sauvignon',
    description: 'Vintage 2018, Napa Valley',
    sku: 'CS-18-002',
    category: 'Wine',
    subcategory: 'Red Wine',
    unit: 'bottle',
    unitCost: 35.0,
    quantityOnHand: 24,
    reorderPoint: 10,
    reorderQuantity: 12,
    supplierId: 'supplier-2',
    notes: 'High demand item',
    defaultSupplierId: 'supplier-2',
    defaultSupplierName: 'Premium Wines',
    cost: 35.0,
    currentStock: 24,
    lowStockThreshold: 10,
    storageLocation: 'Wine Cellar',
    expirationDate: '2028-12-31',
    lotNumber: 'NV2018-10',
    imageUrl: '/placeholder.svg',
    markupPercentage: 60,
    menuItems: ['Wine Pairing Menu', 'Chef\'s Selection'],
    lastCountDate: '2025-05-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '3',
    name: 'Truffle Oil',
    description: 'White truffle infused olive oil',
    sku: 'TO-WH-003',
    category: 'Oil',
    subcategory: 'Specialty Oil',
    unit: 'bottle',
    unitCost: 18.75,
    quantityOnHand: 3,
    reorderPoint: 5,
    reorderQuantity: 8,
    supplierId: 'supplier-1',
    notes: 'Specialty item',
    defaultSupplierId: 'supplier-1',
    defaultSupplierName: 'Italian Imports Co.',
    cost: 18.75,
    currentStock: 3,
    lowStockThreshold: 5,
    storageLocation: 'Dry Storage',
    expirationDate: '2025-10-15',
    lotNumber: 'TR2024-02',
    imageUrl: '/placeholder.svg',
    markupPercentage: 50,
    menuItems: ['Truffle Pasta', 'Risotto'],
    lastCountDate: '2025-05-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '4',
    name: 'Ribeye Steak',
    description: 'Prime grade, 30-day aged',
    sku: 'RB-PR-004',
    category: 'Meat',
    subcategory: 'Beef',
    unit: 'kg',
    unitCost: 42.0,
    quantityOnHand: 8,
    reorderPoint: 4,
    reorderQuantity: 6,
    supplierId: 'supplier-3',
    notes: 'Keep frozen until use',
    defaultSupplierId: 'supplier-3',
    defaultSupplierName: 'Premium Meats',
    cost: 42.0,
    currentStock: 8,
    lowStockThreshold: 4,
    storageLocation: 'Freezer',
    expirationDate: '2025-06-10',
    lotNumber: 'BF2024-15',
    imageUrl: '/placeholder.svg',
    markupPercentage: 45,
    menuItems: ['Steak Dinner', 'Surf and Turf'],
    lastCountDate: '2025-05-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '5',
    name: 'Organic Arugula',
    description: 'Fresh locally-sourced organic arugula',
    sku: 'OA-LC-005',
    category: 'Produce',
    subcategory: 'Leafy Greens',
    unit: 'kg',
    unitCost: 12.0,
    quantityOnHand: 2,
    reorderPoint: 2,
    reorderQuantity: 3,
    supplierId: 'supplier-4',
    notes: 'Ordered twice weekly for freshness',
    defaultSupplierId: 'supplier-4',
    defaultSupplierName: 'Local Organics',
    cost: 12.0,
    currentStock: 2,
    lowStockThreshold: 2,
    storageLocation: 'Walk-in Cooler',
    expirationDate: '2025-05-12',
    lotNumber: 'AR2024-42',
    imageUrl: '/placeholder.svg',
    markupPercentage: 30,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '6',
    name: 'Sparkling Water',
    description: 'Premium Italian sparkling mineral water',
    sku: 'SW-IT-006',
    category: 'Beverages',
    subcategory: 'Water',
    unit: 'case',
    unitCost: 24.0,
    quantityOnHand: 5,
    reorderPoint: 3,
    reorderQuantity: 5,
    supplierId: 'supplier-1',
    notes: '12 bottles per case',
    defaultSupplierId: 'supplier-1',
    defaultSupplierName: 'Italian Imports Co.',
    cost: 24.0,
    currentStock: 5,
    lowStockThreshold: 3,
    storageLocation: 'Dry Storage',
    expirationDate: '2026-05-01',
    lotNumber: 'SW2024-18',
    imageUrl: '/placeholder.svg',
    markupPercentage: 50,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];
